/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesTitleMeetingTermNumberEditRouteImport } from './routes/courses.$title.$meeting.$term.$number.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesTitleMeetingTermNumberEditRoute =
  CoursesTitleMeetingTermNumberEditRouteImport.update({
    id: '/courses/$title/$meeting/$term/$number/edit',
    path: '/courses/$title/$meeting/$term/$number/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses/$title/$meeting/$term/$number/edit': typeof CoursesTitleMeetingTermNumberEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses/$title/$meeting/$term/$number/edit': typeof CoursesTitleMeetingTermNumberEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses/$title/$meeting/$term/$number/edit': typeof CoursesTitleMeetingTermNumberEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courses/$title/$meeting/$term/$number/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courses/$title/$meeting/$term/$number/edit'
  id: '__root__' | '/' | '/courses/$title/$meeting/$term/$number/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesTitleMeetingTermNumberEditRoute: typeof CoursesTitleMeetingTermNumberEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$title/$meeting/$term/$number/edit': {
      id: '/courses/$title/$meeting/$term/$number/edit'
      path: '/courses/$title/$meeting/$term/$number/edit'
      fullPath: '/courses/$title/$meeting/$term/$number/edit'
      preLoaderRoute: typeof CoursesTitleMeetingTermNumberEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesTitleMeetingTermNumberEditRoute:
    CoursesTitleMeetingTermNumberEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
